### ISSUE TITLE
Version tags

### ISSUE THREAD

**Issue by valgur** [PoseLib/PoseLib#103]
Hi!

If it's not too much of a hassle, would it be possible to create Git tags or even GitHub releases for the current and any new versions?

I'm in the process of adding PoseLib as a package to ConanCenter (https://github.com/conan-io/conan-center-index/pull/24770) and I would like to use a real version string, such as the current `2.0.3`, as the package version, but the lack of corresponding Git tags makes it a bit ambiguous whether the current version in the repo is an upcoming or a finished release.

The tags also help with keeping track of newly added versions for package updates: https://qchateau.github.io/conan-center-bot/#/updatable

**Comment by pablospe** [comment]
Something like this?
https://github.com/PoseLib/PoseLib/releases/tag/v2.0.3

@vlarsson: yes, it would be nice create releases of new versions. I was wondering what a good way would be to make this a bit more automatically. Currently the version is in this line:
https://github.com/PoseLib/PoseLib/blob/90f47ffce946569f00f410a528a6a7c4fce5fea2/CMakeLists.txt#L3

Probably it would be good to have a `version.txt` or something external that can be easily parsed? (also to be used in the python binding).

**Comment by valgur** [comment]
@pablospe That's perfect. Thank you!

**Comment by uilianries** [comment]
@pablospe Thank you for your quick action!! :clap:

**Comment by pablospe** [comment]
One more tag:
https://github.com/PoseLib/PoseLib/releases/tag/v2.0.4

**Comment by pablospe** [comment]
Hi @valgur. I was wondering if you could add a small section in the README, so people (including myself) know how to use this. That would be very useful!

**Comment by uilianries** [comment]
@pablospe Hello! I'll open a PR with instructions!
