### ISSUE TITLE
SIGILL in estimate_relative_pose

### ISSUE THREAD

**Issue by MarekKowalski** [PoseLib/PoseLib#110]
Hello! I am getting SIGILL when running PoseLib through GLOMAP (please see the error below). Any idea where the SIGILL may be originating from or how to debug it? It happens on a cloud machine that I cannot connect to directly for debugging, which makes things tricky.

>  Estimating relative pose: 0%*** Aborted at 1723200037 (unix time) try "date -d @1723200037" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGILL (@0x55e9b04ae07c) received by PID 25267 (TID 0x152da24cb640) from PID 18446744072372281468; stack trace: ***
>     @     0x152da6cb9046 (unknown)
>     @     0x152da663b520 (unknown)
>     @     0x55e9b04ae07c poselib::Camera::focal()
>     @     0x55e9b04b9550 poselib::estimate_relative_pose()
>     @     0x55e9afd9174f _ZN6glomap21EstimateRelativePosesERNS_9ViewGraphERSt13unordered_mapIjNS_6CameraESt4hashIjESt8equal_toIjESaISt4pairIKjS3_EEERS2_IjNS_5ImageES5_S7_SaIS8_IS9_SE_EEERKNS_29RelativePoseEstimationOptionsE._omp_fn.0
>     @     0x152da6b74c0e (unknown)
>     @     0x152da668dac3 (unknown)
>     @     0x152da671f850 (unknown)
> Illegal instruction (core dumped)

Please find the dockerfile here [dockerfile.txt](https://github.com/user-attachments/files/16560120/dockerfile.txt)

Thanks a lot,

Marek Kowalski

**Comment by pablospe** [comment]
Could you isolate the use of poselib and reproduce the error? Otherwise, I would suggest posting this issue in glomap repo.

**Comment by vlarsson** [comment]
Hmm. There's not much happening in the poselib::Camera::focal() function, so I guess the problem is somewhere else. I would try re-compiling without -march=native for poselib to see if that helps.

**Comment by pablospe** [comment]
RelativePoseEstimationOptions seems to be the problem, no? Which it is not part of poselib.

Maybe try compiling it without openmp? Just to know if this is related, OPENMP_ENABLED=OFF

Why do you start from `mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04`? You meant this is happening in the cloud machine but when you run it in your machine (the same docker image) it works? Has the cloud machine GPU?

Also, why `-DSIMD_ENABLED=OFF`?

Btw, where is poselib being compiled in the dockerfile you shared? Just to see the options used.

**Comment by MarekKowalski** [comment]
Thanks for the v. quick answers!
>  -march=native for poselib to see if that helps
Good idea, this looks like the potential culprit to me! Trying this right away.

> RelativePoseEstimationOptions seems to be the problem, no? Which it is not part of poselib.
I don't think so, it seems to me that RelativePoseEstimationOptions  is only mentioned as an argument of a method on glomap. Glomap then calls poselib where the error happens.

> Maybe try compiling it without openmp? Just to know if this is related, OPENMP_ENABLED=OFF
Will try.

> Why do you start from mcr.microsoft.com/azureml/openmpi4.1.0-cuda11.8-cudnn8-ubuntu22.04?
That's one of the defaults we use as base AzureML runs. 

> You meant this is happening in the cloud machine but when you run it in your machine (the same docker image) it works
Haven't tried yet, will try eventually if I can't get it to work otherwise. I am on windows and never worked with docker locally so it'll require some fiddling I guess. I also tried building for Windows but not successfully so far.

> Also, why -DSIMD_ENABLED=OFF
To try disabling SIMD which could be responsible for a SIGILL error, it did feel like a fairly long shot though and did not help.

> Btw, where is poselib being compiled in the dockerfile you shared? Just to see the options used.
Poselib is fetched by GLOMAP here https://github.com/colmap/glomap/blob/main/cmake/FindDependencies.cmake

**Comment by vlarsson** [comment]
If you bump poselib to the latest commit in glomap there should be a cmake flag to disable march=native

See here https://github.com/PoseLib/PoseLib/blob/master/CMakeLists.txt#L24

**Comment by MarekKowalski** [comment]
@vlarsson , thanks again for suggesting switching off march native. It fixed the issue for me. Marking this as closed.
