### ISSUE TITLE
scripts to get benchmark against pycolmap

### ISSUE THREAD

**Issue by jeannotes** [PoseLib/PoseLib#118]
in https://user-images.githubusercontent.com/48490995/149815304-b3c1049a-ee64-4c14-be60-d4930535a3e7.png
you benchmark against pycolmap, can you open source the scripts about how to get this image.
thanks.

**Comment by vlarsson** [comment]
Hey,
I am not sure if I still have the code for setting up this image. There is some benchmarking setup in https://github.com/vlarsson/posebench
It would be good if posebench could generate this type of image as well.
