### ISSUE TITLE
obtain estimated focal length from robust estimator pose/info

### ISSUE THREAD

**Issue by mich2k** [PoseLib/PoseLib#119]
Hello!

Pretty much what the title said, how can i get the estimated focal length from a CameraPose struct when enabling https://arxiv.org/abs/2311.16304 ?

plus: is there a way to estimate focal length with a robust estimator for a single camera absolute pose with this library? Or the only viable solution atm is p4pf?

If it matters i'm on pybind

Thank you!

**Comment by kocurvik** [comment]
The CameraPose struct does not provide any information on focal lengths. If you have two images with 2d-2d correspondences and want to get focal lenghts you should
1) If you have two different cameras - run `estimate_fundamental` -> `focals_from_fundamental_iterative` for our method or `focals_from_fundamental` for the Bougnoux formula
2) If you have the same cameras you should use `estimate_shared_focal_relative_pose`

In case you have some 2d-3d correspondences then you should use the p4pf solver. You should check out the `dev` branch it is still in development, but you may find some code there for bundle adjustment for this problem using different cameras.
