### ISSUE TITLE
Adding 6pt relative pose with unknown equal focals + other intrinsic refinement methods

### ISSUE THREAD

**Issue by kocurvik** [PoseLib/PoseLib#89]
Hello,

I have a question about potential contributions. For our [recent paper](https://arxiv.org/abs/2311.16304) I have implemented a solver for relative pose with unknown focal length equal for both cameras + its LO into PoseLib. In the paper we propose to perform degeneracy checks for imaginary focal lengths (denoted RFC) generally improving both speed and accuracy of fundamental matrices and an iterative method to estimate the focal lengths from fundamental matrices.

In the repo for the paper [I got asked to contribute to PoseLib](https://github.com/kocurvik/robust_self_calibration/issues/1). I would gladly prepare a PR, but in one of the issues I found this relatively recent (Oct 2023) comment:

              @alexs7 the code is currently not in PoseLib. It's on my todo to add instrinsic refinement and once this is added I plan to add all of the corresponding solvers for unknown intrinsics.

_Originally posted by @vlarsson in https://github.com/PoseLib/PoseLib/issues/16#issuecomment-1746854692_

So I am not sure whether some code is already prepared. My question is therefore which of these would be welcome contributions. If any of them would be welcome, then I would appreciate some information on what testing or benchmarking is required for PRs.

**Comment by vlarsson** [comment]
I saw your paper, nice work! It would be great if you could make a PR for this.

Regarding the comment, there is currently a WIP branch that refactors the camera models (https://github.com/PoseLib/PoseLib/tree/camera_models), and my original plan was to look into intrinsic+distortion parameter refinement after this, but I am not sure when I will find the time for this :) But even then, when this happens it will be easier if your code is integrated already.

**Comment by vlarsson** [comment]
Regarding testing. If you want, you could also setup a PR for https://github.com/vlarsson/posebench that also tests the F estimators.

**Comment by kocurvik** [comment]
> Regarding testing. If you want, you could also setup a PR for https://github.com/vlarsson/posebench that also tests the F estimators.

Thanks. I will look into it.
