### ISSUE TITLE
Can PoseLib be used for extrinsic camera caliberation?

### ISSUE THREAD

**Issue by aviralchharia** [PoseLib/PoseLib#90]
Suppose we have a $3$ camera setup. In such a case, can $PoseLib$ be used to get the camera extrinsic parameters? Traditionally, using checkerboards, for $3$ cameras, we use $[C1, C2]$, $[C2, C3]$ pairs to find the extrinsic matrices of the cameras while assuming one of the cameras as the root/ origin.

**Comment by vlarsson** [comment]
Currently there are no three-view estimators implemented in PoseLib. I suggest running two-view estimation (essential matrix) between the first two images. You can then triangulate 3D points that can be used to register the third camera (via absolute pose / pnp). You could also run two sequential two-view estimations, but then you would need to solve for the relative scale separately.

**Comment by vlarsson** [comment]
Yes, I think that should be doable. I suggest setting up a good model refinement (some kind of bundle adjustment) as well. Good luck :)
